TRUNCATE METRIC RESTART IDENTITY;

CREATE TABLE METRIC
(
    ID               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME             VARCHAR                           NOT NULL,
    VALUE             VARCHAR                          NOT NULL
);